<?php include 'buffer.inc'; ?>
    <h2 class="subtitle">About</h2>

    <div class="content-container">
      <div class="scroll-content" id="scrollable">
        <h3>Background</h3>
        <p>The Sea Escape idea came out of a half term planning session for <a href="https://www.chorltonscouts.org.uk/">Chorlton &amp; Northenden Scouts</a>.</p>
        <p>Over the last few years, the group has established a number of new Sea Scout troops, the first coming into existence around 2020, I think. Chorlton &amp; Northenden Scouts have excellent water season paddle sports activities. As a former Sea Scout myself (ahem 30 years ago), who learned to kayak and sail dinghies as a child, I decided to volunteer to join the Sea Scout leadership team. Over the last few years, I have put myself through various courses to hone my somewhat rusty watersports skills. I enjoyed studying various RYA courses and I thought I might introduce some of the background and theory elements of Seamanship during our off-water seasons, if I could. Midway through last Autumn term (2024), at our usual planing meeting, I suggested I could bring in some of the of the elements of the RYA's Essential Navigation and Seamanship and VHF radio sylibus. Lenny, my section's Team Lead, suggested that an escape room format could be a good way to do this, and thus was born the idea of Grey Wolf's Sea Escape.</p>
        <p>I had already started looking to bring in elements of the VHF short range certificate, into an offering for <a href="https://www.jotajoti.info/">JOTA</a>, so to make it more relevant to our Sea Scouts. There, I was attempting to tie in some of my innate Amateur Radio skillz which I had already used for a <a href="https://23rdmanchester.uk/our-jamboree-on-the-air/">23rd Manchester JOTA camp</a>. To that end I had been engineering a Marine Radio Simulator with DSC and relevant channel selection: all the features you might expect on a modern ship's VHF radio. I wanted to give hands on experience without the outlay on equipment and to avoid accidental transmission on marine bands. I have deployed a pre-release version of this radio simulator as part of the escape room.</p>
        <h3>Assembling content</h3>
        <p>Taking this radio simulator, and mixing it up a little with RYA theory, throwing in a few drops of whimsey in the form of a piratical theme and sea myths, I created Grey Wolf's Sea Escape. After delivering this with physical maps and plotters designed in <a target="_blank" href="https://inkscape.org/">inkscape</a>, treasure chests and similar paraphernalia bought online, and training almanacs, charts etc. supplied as part of my RYA training (which I did online at <a href="https://sailtrain.org.uk/">Sailtrain</a>); I have subsequently endeavoured <span class="tooltip"><span class="tooltiptext">Our sections are named after significant ships from our naval history. My section is named Endeavour.</span>(pun intended)</span> to make the whole experience available online. However you choose to use the content here, I hope your Scouts will enjoy meeting a Kracken, Sirens, the Black Pearl, perhaps a pseudo-cameo appearance of a certain Captain Sparrow, while learning about elements of marine radio, buoyage and basic maritime navigation.</p>
        <h3>First Setup</h3>
        <p>The SeaEscape was originlally set up for six partrols based in and around our scout hut. Each patrol was given a colour and a number needed for the clues. They were also given an <span class="tooltip"><span class="tooltiptext">I found Safari/iPad awkward, and make no apology for Apple's 'features' degrading your experience.</span>iPad</span> to use for the first parts of the activity a search and rescue. With this kit they were given an initial direction to locate and retrieve the first clue using far-too-specific Latitude and Longitude coordinates; using google maps (or similar) to pin-point a storage container set somewhere around the scout hut grounds. Once there, they would find a fictitious <a href="/assets/Chart.pdf">chart</a> made to look like an Admarilty/Imray Chart. They would also receive instructions for the location in naughtical terms of the next clue and also a means to make a plotter (plotters are relatively expensive). Subsequent clues where hidden in tiny colour-coded locked chests secreted about the hut.</p>
        <h3>Inventory</h3>
        <p>For the <span class="tooltip"><span class="tooltiptext">mostly offline!</span>offline</span> setup:</p>
          <ul>
            <li>One 'large' prize chest (&approx;20x10x5cm) with a lock and 6 spare keys</li>
            <li>Chocolate coins, for the prize in that chest. (Lidl had coins at Christmas with an embossed fleur-de-lis).</li>
            <li>30 tiny chests.</li>
            <li>24 mini hasp and staples</li>
            <li>24 combination locks the colours dictating the teams.</li>
            <li>6 A3 printouts of the <a href="/assets/Chart.pdf">Chart</a>. Some libraries have A3 printers.</li>
            <li>6 A4 transparency printouts of a <a href="/assets/Plotter.pdf">kit form plotter</a></li>
            <li>Press studs for the plotter kit. (Could just use a drawing pin and blu-tak.)</li>
            <li>A small library of Nautical info, e.g. an Alminac, a Chart key, a glossary of nautical terms e.g. <a href="https://www.grenadabluewatersailing.com/sailing-terminology-glossary/">this one</a>.</li>
          </ul>
        <p>The only essential parts of this kit for the mostly offline version are charts and plotter printouts, and perhaps a glossary and chart key. One could have a leader hand out clues upon receipt of correct code. Otherwise <a href="https://www.amazon.co.uk/hz/wishlist/ls/27FOH60HUE97?ref_=wl_share">here's an Amazon list</a> for most of the above.</p>
        <p>After I delivered the event, I thought about how to make it more widely available. So here it is. With a few updates. It can now all be done, more-or-less online.</p>
        <a name="complementary"></a>
        <h3>Sustainablity</h3>
        <p>The wholly online version is hosted on a VM run and paid for by yours truly. As such it will only remain available while I can justify the cost. Making a donation via the registration page, one way or another, will get you immediate access. If you are unable to justify even a small donation, you should contact me if you wish to make use of this service: <span aria-label="This email address is obfuscated. Please obtain my email address by other means." style="font-family: ScrambleN;">&lt;89;.$A@;:*&lt;#@:AB4D:FAB4:.A,+.B9</span>. Access rights last one month from registration but I can extend that upon request.</p>
        <h3>Warranty, or lack thereof</h3>
        <p>This software comes with no warranty and is maintained only with best efforts, as you might expect squeezing it into my Scout volunteer's &quot;one hour a week&quot;.</p>
        <p>The code can be found on GitHub, in the public repository <a href="https://github.com/nimpo/GreyWolfsSeaEscapeOnline">nimpo/GreyWolfsSeaEscapeOnline</a>. Should you discover a problem or if you have a feature request you can raise it <a href="https://github.com/nimpo/GreyWolfsSeaEscapeOnline/issues">there</a>.</p>
        <h3>Compatibility</h3>
        <p>Your participants will need to log into the service on a device. I would suggest you try your devices, where possible, for suitablity before running a session. I am happy to receive reports of the software not working, and am likely to be as frustrated and potentially as baffled as you if that happens. Some of the tooling used requiers a resonably modern browser, but you have one of those; you update your browser regularly for security reasons, right?</p>
        <p>This has been developed on a GNU/Linux machine running Ubuntu and KDE. There I tested the Sea Escape in great depth using Google Chrome and Firefox. It has also been tested on Edge in a Windows 11 VM, on Chrome and Firefox on my Android phone, a Samsung tablet and in Safari and Chrome on an iOS tablet, (though supporting iOS required a major refactoring of the code). Ultimately, not all browsers are made equally, and so your mileage may vary.</p>
        <h3>Cookies and other tracking</h3>
        <p>Cookies will be set to identify patrols/teams for the purpose of serving the relevant content to their sessions and tracking progress through the questions. Cookies are also set during regirstration protocol handshake for leaders. They can be wiped in the usual way at your discretion and should disappear after the session, and in any case after the access to the system has expired 31 days after registering. Group based usernames will be set for your leaders to manage access on behalf of your group. IP addresses are also stored as part of the usual logging facility for protection and maintenance of this service and will clear based on sensible log rotation rules.</p>
      </div>
    </div>
    <div class="bottom-links">
      <p style="margin-block-start:2px"><a href="/about/">about</a> | <a href="/notes/">leaders-notes</a> | <a href="/leaders/private/">leader-login&nbsp;&#128274;</a> | <a href="/register/">register</a> | <a href="/">home</a></p>
    </div>
