<?php
$answers=array();
$answers['leaders']  = array('Jack','543','109','220','805');
$answers['black']  = array('Jack','564','074','212','867');
$answers['yellow'] = array('Jack','521','062','125','644');
$answers['silver'] = array('Jack','327','082','238','864');
$answers['blue']   = array('Jack','231','136','234','466');
$answers['purple'] = array('Jack','564','356','224','845');
$answers['pink']   = array('Jack','342','296','287','802');
?>
