name: Apache & PHP Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y sox libsox-fmt-mp3 openssl php apache2 curl libapache2-mod-php

      - name: Configure Apache Virtual Host
        run: |
          sudo cp -r . /var/www/seascouts
          bash /var/www/seascouts/bin/setupPermissions.sh -y
          bash /var/www/seascouts/bin/newAccount.sh -y -t test1
          echo "127.0.1.98 seascouts.example.org" |sudo tee -a /etc/hosts
          sudo openssl genpkey -algorithm RSA -out /var/www/seascouts/etc/key.pem
          sudo openssl req -new -key /var/www/seascouts/etc/key.pem -out csr.pem -subj "/CN=seascouts.example.org"
          sudo openssl x509 -req -days 1 -in csr.pem -signkey /var/www/seascouts/etc/key.pem -out /var/www/seascouts/etc/cert.pem >/dev/null 2>&1
          sudo cp /var/www/seascouts/etc/cert.pem /var/www/seascouts/etc/chain.pem
          sudo cp /var/www/seascouts/etc/cert.pem /etc/ssl/certs/$(openssl x509 -in /var/www/seascouts/etc/cert.pem -noout -hash).0
          sudo cp /var/www/seascouts/etc/seascouts.conf /etc/apache2/sites-available/
          sudo a2enmod ssl cgi
          sudo a2dissite 000-default
          sudo a2ensite seascouts.conf
          # Restart Apache
          sudo systemctl restart apache2

      - name: Verify Apache 
        run: |
          sleep 5
          systemctl status apache2 --no-pager || exit 1

      - name: Check landing page
        run: |
          curl -s -L --fail "https://seascouts.example.org/"

      - name: Check Escape Private Page
        run: |
          curl -s -L -u Test1-black:test-scout --fail "https://seascouts.example.org/escape/"

      - name: Check Leaders Private Page
        run: |
          curl -s -L -u Test1-leaders:test-leader --fail "https://seascouts.example.org/leaders/private/"

      - name: Check PlaceJack
        run: |
          curl -s -L -u Test1-leaders:test-leader -G -d "lat=53.449906" -d "lng=-2.215405" -d "len=30" --fail "https://seascouts.example.org/leaders/private/placejack/anchor"

      - name: Check Bounds
        run: |
          sleep 5
          curl -s -L -u Test1-black:test-scout --fail "https://seascouts.example.org/escape/findjack/bounds" |grep '{"lat":53.449906,"lng":-2.215405,"len":30}'

      - name: Check Audio Was Produced
        run: |
          sleep 90
          curl -s -I -L -u Test1-black:test-scout "https://seascouts.co.uk/escape/audio" |grep 'Content-Type: audio/mpeg'      

      - name: Check Finding Jack
        run: |
          curl -s -L -u Test1-black:test-leader -d "team=1" -d "Q=0" -d -d "lat=53.449907" -d "lon=-2.215404" --fail "https://seascouts.example.org/escape/foundjack/"

      - name: Print Apache Logs on Failure
        if: failure()
        run: |
          echo "Apache Error Logs:"
          sudo journalctl -u apache2 --no-pager | tail -n 50
          sudo tail -n 50 /var/log/apache2/seascouts_error.log
          ls -l /var/www/seascouts/html/escape/audio
